{% set name = "cdlib" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cdlib-{{ version }}.tar.gz
  sha256: 31623d498c29e5b079a24ebff48098d8f28e372e829dfeea4af41285db7e9065

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - numpy
    - matplotlib-base
    - scikit-learn
    - tqdm
    - networkx >=3.0
    - demon
    - python-louvain >=0.16
    - scipy
    - pulp
    - seaborn
    - pandas
    - eva-lcd
    - bimlpa
    - python-igraph >=0.10
    - angelcommunity
    - pooch
    - dynetx
    - thresholdclustering
    - python-Levenshtein
    - plotly

test:
  imports:
    - cdlib
  requires:
    - pip

about:
  home: https://github.com/GiulioRossetti/cdlib
  summary: Community Discovery Library
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mediocretech
